version: "2.28"

services:
  backend:
    container_name: Backend-container
    restart: unless-stopped
    image: my-backend-image:1.0.0
    ports:
      - "8000:8000"
    build:
      context: BackEnd
      dockerfile: Dockerfile
    networks: 
      - shared-network

  frontend:
    container_name: frontend-container
    restart: unless-stopped
    image: rural-frontend-image:1.0.0
    ports:
      - "3000:3000"
    build:
      context: FrontEnd
      dockerfile: Dockerfile
    networks: 
      - shared-network

  python-ml:
    container_name: pythonml-container
    restart: unless-stopped
    build:
      context: Model  # Updated to match your Python model folder
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Updated port to match the one exposed in your Dockerfile
    networks: 
      - shared-network
    depends_on:
      - backend

networks:
  shared-network:
